INSERT INTO products (product_id,name,category,price) values (1,'Calendar','Bright office',42);
INSERT INTO products (product_id,name,category,price) values (2,'Wish-list','Bright office',56);
INSERT INTO products (product_id,name,category,price) values (3,'Travel Map','Bright office',71);
INSERT INTO products (product_id,name,category,price) values (4,'Wall Mirror','Bright office',101);
INSERT INTO products (product_id,name,category,price) values (5,'Launch Box','Bright office',42);
INSERT INTO products (product_id,name,category,price) values (6,'Fishpool','Bright office',72);
INSERT INTO products (product_id,name,category,price) values (7,'Set of Markers','Bright office',24);
INSERT INTO products (product_id,name,category,price) values (8,'Desktop Fan','Bright office',84);
INSERT INTO products (product_id,name,category,price) values (9,'Wall Clock','Cozy house',65);
INSERT INTO products (product_id,name,category,price) values (10,'Organizer for Scarves','Cozy house',194);
INSERT INTO products (product_id,name,category,price) values (11,'Jewelry Holder','Cozy house',226);
INSERT INTO products (product_id,name,category,price) values (12,'Frame','Cozy house',49);
INSERT INTO products (product_id,name,category,price) values (13,'Set of Hangers','Cozy house',62);
INSERT INTO products (product_id,name,category,price) values (14,'Lamp','Cozy house',56);
INSERT INTO products (product_id,name,category,price) values (15,'Set of Mugs','Kitchen',65);
INSERT INTO products (product_id,name,category,price) values (16,'Glasses','Kitchen',28);
INSERT INTO products (product_id,name,category,price) values (17,'Plate','Kitchen',17);
INSERT INTO products (product_id,name,category,price) values (18,'Ice Cream Mold','Kitchen',84);
INSERT INTO products (product_id,name,category,price) values (19,'Salt Shaker and Pepper Shaker','Kitchen',92);
INSERT INTO products (product_id,name,category,price) values (20,'Cocktail Straws','Kitchen',24);
